function spec = excel_write_detail(T, cfg)
%EXCEL_WRITE_DETAIL  Build the data specification (spec) for the Detail sheet
%
%   spec = excel_write_detail(T, cfg)
%
%   T   — MATLAB table (data loaded from search_results JSONL or CSV)
%   cfg — Runtime configuration struct (referenced only by this function)
%
%   Return value spec:
%     .sheetName  (string)       — 'Detail'
%     .headers    (cell 1×N)     — Header row
%     .data       (cell nRows×N) — Data
%     .hyperlinks (struct array) — {row, col, url, display} (DOI links)
%
%   Column definition (33 columns):
%     Overview 8 columns + openalex_id / first_author_name / first_author_institution /
%     last_author_name / last_author_institution / doi_normalized / publication_date /
%     fwci / citation_percentile / counts_by_year / is_retracted / best_oa_pdf_url /
%     license / referenced_works_count / open_access_url / pdf_status /
%     keyword_evidence / language / topics / mentions_dataset / mentions_code /
%     mentions_library / mentions_metrics / repro_signal_score / matlab_mentioned
%
%   Notes:
%     - Columns not generated by the pipeline are output as empty strings
%     - Abstract is truncated to the first 8000 characters (within Excel cell limit of 32767)

arguments
    T   table
    cfg struct = struct()
end

ABSTRACT_MAX = 8000;
n = height(T);
keywords = local_extract_keywords(cfg);

headers = { ...
    'title', 'DOI', 'publication_year', 'cited_by_count', 'is_oa', 'source_name', 'type', 'abstract', ...
    'openalex_id', 'first_author_name', 'first_author_institution', 'last_author_name', 'last_author_institution', ...
    'doi_normalized', 'publication_date', 'fwci', 'citation_percentile', 'counts_by_year', 'is_retracted', ...
    'best_oa_pdf_url', 'license', 'referenced_works_count', 'open_access_url', 'pdf_status', 'keyword_evidence', ...
    'language', 'topics', 'mentions_dataset', 'mentions_code', 'mentions_library', 'mentions_metrics', ...
    'repro_signal_score', 'matlab_mentioned'};
nCols  = numel(headers);
data   = cell(n, nCols);
hyperlinks = struct('row', {}, 'col', {}, 'url', {}, 'display', {});

for r = 1:n
    % 1: Title
    data{r,1} = local_str(T, 'title', r);

    % 2: DOI (hyperlink)
    doiVal = local_str(T, 'doi', r);
    data{r,2} = doiVal;
    if numel(doiVal) > 0
        hyperlinks(end+1) = struct( ...
            'row',     r + 1, ...
            'col',     2, ...
            'url',     ['https://doi.org/' doiVal], ...
            'display', doiVal); %#ok<AGROW>
    end

    % 3–8: Overview common columns
    data{r,3} = local_num(T, 'publication_year', r);
    data{r,4} = local_num(T, 'cited_by_count', r);
    data{r,5} = local_is_oa(T, r);

    srcName = local_str(T, 'source_name', r);
    if isempty(srcName)
        srcName = local_str(T, 'source_dataset', r);
    end
    data{r,6} = srcName;

    data{r,7} = local_str(T, 'type', r);

    absTxt = local_str(T, 'abstract', r);
    if length(absTxt) > ABSTRACT_MAX
        absTxt = [absTxt(1:ABSTRACT_MAX), '...'];
    end
    absTxt = local_highlight_keywords(absTxt, keywords);
    data{r,8} = absTxt;

    % 9: OpenAlex ID
    data{r,9} = local_str(T, 'openalex_id', r);

    % 10: First author name
    data{r,10} = local_str(T, 'first_author_name', r);

    % 11: First author affiliation (first_author_institution / first_author_institutions)
    inst = local_str(T, 'first_author_institution', r);
    if isempty(inst)
        inst = local_str(T, 'first_author_institutions', r);
    end
    data{r,11} = inst;

    % 12: Corresponding author name
    data{r,12} = local_str(T, 'last_author_name', r);

    % 13: Corresponding author affiliation (last_author_institution / last_author_institutions)
    lastInst = local_str(T, 'last_author_institution', r);
    if isempty(lastInst)
        lastInst = local_str(T, 'last_author_institutions', r);
    end
    data{r,13} = lastInst;

    % 14: DOI (normalized)
    data{r,14} = local_str(T, 'doi_normalized', r);

    % 15: Publication date
    data{r,15} = local_str(T, 'publication_date', r);

    % 16: Field-weighted citation impact
    data{r,16} = local_num(T, 'fwci', r);

    % 17: Citation percentile
    data{r,17} = local_num(T, 'citation_percentile', r);

    % 18: Counts by year raw JSON
    data{r,18} = local_str(T, 'counts_by_year', r);

    % 19: Retracted flag
    retractVal = local_num(T, 'is_retracted', r);
    if isnumeric(retractVal)
        if retractVal == 1
            data{r,19} = 'Yes';
        elseif retractVal == 0
            data{r,19} = 'No';
        else
            data{r,19} = '';
        end
    else
        data{r,19} = '';
    end

    % 20: Best OA PDF URL
    data{r,20} = local_str(T, 'best_oa_pdf_url', r);

    % 21: License
    data{r,21} = local_str(T, 'license', r);

    % 22: Referenced works count
    data{r,22} = local_num(T, 'referenced_works_count', r);

    % 23: OA paper URL
    data{r,23} = local_str(T, 'open_access_url', r);

    % 24: PDF status
    data{r,24} = local_str(T, 'pdf_status', r);

    % 25: Keyword evidence (evidence_text or keyword_evidence column)
    evTxt = local_str(T, 'evidence_text', r);
    if isempty(evTxt)
        evTxt = local_str(T, 'keyword_evidence', r);
    end
    data{r,25} = evTxt;

    % 26: Language
    data{r,26} = local_str(T, 'language', r);

    % 27: Topics
    data{r,27} = local_str(T, 'topics', r);

    % 28–31: Repro signal flags
    data{r,28} = local_yes_no(T, 'mentions_dataset', r);
    data{r,29} = local_yes_no(T, 'mentions_code', r);
    data{r,30} = local_yes_no(T, 'mentions_library', r);
    data{r,31} = local_yes_no(T, 'mentions_metrics', r);

    % 32: Repro signal score
    data{r,32} = local_num(T, 'repro_signal_score', r);

    % 33: MATLAB mentioned
    mlMent = local_str(T, 'matlab_mentioned', r);
    if strcmpi(mlMent, '1') || strcmpi(mlMent, 'true')
        mlMent = 'Yes';
    elseif strcmpi(mlMent, '0') || strcmpi(mlMent, 'false')
        mlMent = '';
    end
    data{r,33} = mlMent;
end

spec = struct();
spec.sheetName  = 'Detail';
spec.headers    = headers;
spec.data       = data;
spec.hyperlinks = hyperlinks;
spec.nCols      = nCols;
end

% ─── Local helpers ────────────────────────────────────────────────────────────────

function v = local_str(T, col, row)
v = '';
if ~ismember(col, T.Properties.VariableNames)
    return;
end
raw = T.(col)(row);
if isstring(raw)
    if ~ismissing(raw)
        v = char(raw);
    end
elseif ischar(raw)
    v = raw;
elseif isnumeric(raw) || islogical(raw)
    if ~isnan(double(raw))
        v = char(string(raw));
    end
end
end

function v = local_num(T, col, row)
v = '';
if ~ismember(col, T.Properties.VariableNames)
    return;
end
raw = T.(col)(row);
if isnumeric(raw) && isscalar(raw) && ~isnan(raw)
    v = double(raw);
elseif islogical(raw) && isscalar(raw)
    v = double(raw);
end
end

function s = local_is_oa(T, row)
s = '';
if ~ismember('is_oa', T.Properties.VariableNames)
    return;
end
raw = T.is_oa(row);
if islogical(raw)
    if raw; s = 'Yes'; else; s = 'No'; end
elseif isnumeric(raw)
    if raw == 1; s = 'Yes'; elseif raw == 0; s = 'No'; end
elseif isstring(raw) || ischar(raw)
    sv = lower(strtrim(char(string(raw))));
    if any(strcmp(sv, {'true','1','yes'}))
        s = 'Yes';
    elseif numel(sv) > 0
        s = 'No';
    end
end
end

function s = local_yes_no(T, col, row)
s = '';
if ~ismember(col, T.Properties.VariableNames)
    return;
end
raw = T.(col)(row);
if islogical(raw)
    if raw; s = 'Yes'; end
elseif isnumeric(raw)
    if raw == 1; s = 'Yes'; end
elseif isstring(raw) || ischar(raw)
    sv = lower(strtrim(char(string(raw))));
    if any(strcmp(sv, {'true','1','yes'}))
        s = 'Yes';
    end
end
end

function keywords = local_extract_keywords(cfg)
% Extract keyword list from cfg.query (for highlighting)
keywords = {};
if ~isfield(cfg, 'query') || isempty(cfg.query)
    return;
end
q = strtrim(char(string(cfg.query)));
if isempty(q)
    return;
end
% Split by | for OR → split by space for AND → remove quotation marks
orParts = strsplit(q, '|');
for i = 1:numel(orParts)
    words = strsplit(strtrim(orParts{i}), ' ');
    for j = 1:numel(words)
        w = strtrim(words{j});
        w = regexprep(w, '^"|"|^''|''$', '');  % Remove quotation marks
        if length(w) >= 2
            keywords{end+1} = w; %#ok<AGROW>
        end
    end
end
keywords = unique(keywords, 'stable');
end

function txt = local_highlight_keywords(txt, keywords)
% Surround keywords in abstract text with 《》keyword》《 (case-insensitive)
if isempty(txt) || isempty(keywords)
    return;
end
for i = 1:numel(keywords)
    kw = keywords{i};
    if isempty(kw); continue; end
    % Escape special regex characters
    kw_esc = regexprep(kw, '([\\\^\$\.\|\?\*\+\(\)\{\}\[\]])', '\\$1');
    txt = regexprep(txt, ['(?i)(' kw_esc ')'], [char(12304) '$1' char(12305)]);
end
end
