function result = export_bibtex(jsonlPath, outDir, options)
%EXPORT_BIBTEX  Generate BibTeX (.bib) and RIS (.ris) from search_results.jsonl
%
%   export_bibtex(jsonlPath, outDir)
%   result = export_bibtex(jsonlPath, outDir, Name=Value, ...)
%
%   Arguments:
%     jsonlPath (string) — Input JSONL file path (.csv also accepted)
%     outDir    (string) — Output directory path
%
%   [Name=Value options]
%     enableBibtex  : Output BibTeX (.bib) (default: true)
%     enableRis     : Output RIS (.ris)    (default: true)
%     outputBib     : Output .bib file path (default: outDir/search_results.bib)
%     outputRis     : Output .ris file path (default: outDir/search_results.ris)
%
%   [Return value] result struct
%     .bib_path     — Generated .bib file path ("" if not generated)
%     .ris_path     — Generated .ris file path ("" if not generated)
%     .rows_written — Number of entries written
%
%   BibTeX type mapping:
%     article / review                → @article
%     conference-paper / proceedings  → @inproceedings
%     book                            → @book
%     book-chapter                    → @incollection
%     other                           → @misc
%
%   RIS type mapping:
%     article / review                → JOUR
%     conference-paper / proceedings  → CONF
%     book                            → BOOK
%     book-chapter                    → CHAP
%     other                           → GEN

arguments
    jsonlPath        (1,1) string
    outDir           (1,1) string
    options.enableBibtex (1,1) logical = true
    options.enableRis    (1,1) logical = true
    options.outputBib    (1,1) string  = ""
    options.outputRis    (1,1) string  = ""
end

result.bib_path    = "";
result.ris_path    = "";
result.rows_written = int32(0);

% Utility path setup (read_jsonl etc.)
local_addpath_util(mfilename('fullpath'));

% Load input data
T = local_load_data(jsonlPath);
if height(T) == 0
    log_warn("export_bibtex: input data is empty: %s", jsonlPath);
    return;
end

% Ensure output directory exists
if strlength(outDir) > 0 && ~isfolder(outDir)
    mkdir(outDir);
end

% Output paths
bibPath = options.outputBib;
if strlength(bibPath) == 0
    bibPath = string(fullfile(char(outDir), 'search_results.bib'));
end
risPath = options.outputRis;
if strlength(risPath) == 0
    risPath = string(fullfile(char(outDir), 'search_results.ris'));
end

n = height(T);
usedKeys = {};

% ── BibTeX generation ──────────────────────────────────────────────────────────
if options.enableBibtex
    fid = fopen(char(bibPath), 'w', 'n', 'UTF-8');
    if fid < 0
        log_warn("export_bibtex: failed to open .bib file: %s", bibPath);
    else
        cleanup = onCleanup(@() fclose(fid));
        fprintf(fid, '%% Generated by AnyResearch — %s\n\n', ...
            char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')));
        for r = 1:n
            key  = local_bibtex_key(T, r, usedKeys);
            usedKeys{end+1} = key; %#ok<AGROW>
            entry = local_build_bibtex_entry(T, r, key);
            fprintf(fid, '%s\n\n', char(entry));
        end
        result.bib_path    = bibPath;
        result.rows_written = int32(n);
        log_info("export_bibtex: wrote %d entries → %s", n, bibPath);
    end
end

% ── RIS generation ─────────────────────────────────────────────────────────────
if options.enableRis
    fid2 = fopen(char(risPath), 'w', 'n', 'UTF-8');
    if fid2 < 0
        log_warn("export_bibtex: failed to open .ris file: %s", risPath);
    else
        cleanup2 = onCleanup(@() fclose(fid2));
        for r = 1:n
            entry = local_build_ris_entry(T, r);
            fprintf(fid2, '%s\n', char(entry));
        end
        result.ris_path = risPath;
        if result.rows_written == 0
            result.rows_written = int32(n);
        end
        log_info("export_bibtex: wrote %d RIS entries → %s", n, risPath);
    end
end
end

% ── BibTeX key generation ──────────────────────────────────────────────────────

function key = local_bibtex_key(T, r, usedKeys)
nm = local_col_str(T, 'first_author_name', r);
yr = local_col_str(T, 'publication_year', r);
ti = local_col_str(T, 'title', r);

% Author last name
lastName = '';
if ~isempty(nm)
    if contains(nm, ',')
        parts = strsplit(nm, ',');
        lastName = strtrim(parts{1});
    else
        words = strsplit(strtrim(nm), ' ');
        lastName = words{end};
    end
    lastName = lower(regexprep(lastName, '[^a-zA-Z]', ''));
end
if isempty(lastName)
    lastName = 'anon';
end

% First meaningful word from the title (excluding stop words)
stopWords = {'a','an','the','of','in','on','for','and','or','with','to', ...
             'from','by','is','are','was','were','this','that','these','those'};
titleWord = '';
tiWords = strsplit(lower(regexprep(ti, '[^a-zA-Z ]', ' ')));
for i = 1:numel(tiWords)
    w = strtrim(tiWords{i});
    if length(w) >= 3 && ~any(strcmp(w, stopWords))
        titleWord = w;
        break;
    end
end
if isempty(titleWord)
    titleWord = 'notitle';
end

baseKey = [lastName yr titleWord];
if isempty(strtrim(baseKey))
    baseKey = 'paper';
end

% Ensure uniqueness
key = baseKey;
if any(strcmp(usedKeys, key))
    for si = 1:26
        candidate = [baseKey char('a' + si - 1)];
        if ~any(strcmp(usedKeys, candidate))
            key = candidate;
            break;
        end
    end
end
end

% ── BibTeX entry construction ───────────────────────────────────────────────────

function entry = local_build_bibtex_entry(T, r, key)
typeStr  = local_col_str(T, 'type', r);
btype    = local_bibtex_type(typeStr);
title    = local_bib_escape(local_col_str(T, 'title', r));
doi      = local_col_str(T, 'doi', r);
yr       = local_col_str(T, 'publication_year', r);
srcName  = local_bib_escape(local_col_str(T, 'source_name', r));
abstract = local_bib_escape(local_col_str(T, 'abstract', r));

% Author list (first_author_name + last_author_name, deduplicated)
firstAuth = strtrim(local_col_str(T, 'first_author_name', r));
lastAuth  = strtrim(local_col_str(T, 'last_author_name', r));
authors = {};
if ~isempty(firstAuth)
    authors{end+1} = firstAuth;
end
if ~isempty(lastAuth) && ~strcmpi(lastAuth, firstAuth)
    authors{end+1} = lastAuth;
end
if numel(authors) > 1
    authorStr = strjoin(authors, ' and ');
elseif numel(authors) == 1
    authorStr = authors{1};
else
    authorStr = '';
end

lines = {};
lines{end+1} = sprintf('@%s{%s,', btype, key);
if ~isempty(authorStr)
    lines{end+1} = sprintf('  author  = {%s},', local_bib_escape(authorStr));
end
if ~isempty(title)
    lines{end+1} = sprintf('  title   = {%s},', title);
end
switch btype
    case 'article'
        if ~isempty(srcName)
            lines{end+1} = sprintf('  journal = {%s},', srcName);
        end
    case 'inproceedings'
        if ~isempty(srcName)
            lines{end+1} = sprintf('  booktitle = {%s},', srcName);
        end
    case {'book', 'incollection'}
        if ~isempty(srcName)
            lines{end+1} = sprintf('  publisher = {%s},', srcName);
        end
end
if ~isempty(yr)
    lines{end+1} = sprintf('  year    = {%s},', yr);
end
if ~isempty(doi)
    lines{end+1} = sprintf('  doi     = {%s},', doi);
    lines{end+1} = sprintf('  url     = {https://doi.org/%s},', doi);
end
if ~isempty(abstract)
    % Truncate abstract to first 500 chars (BibTeX handles long values poorly)
    if length(abstract) > 500
        abstract = [abstract(1:497), '...'];
    end
    lines{end+1} = sprintf('  abstract = {%s},', abstract);
end
lines{end+1} = '}';

entry = string(strjoin(lines, newline));
end

% ── RIS entry construction ─────────────────────────────────────────────────────

function entry = local_build_ris_entry(T, r)
typeStr  = local_col_str(T, 'type', r);
risType  = local_ris_type(typeStr);
title    = local_col_str(T, 'title', r);
doi      = local_col_str(T, 'doi', r);
yr       = local_col_str(T, 'publication_year', r);
srcName  = local_col_str(T, 'source_name', r);
abstract = local_col_str(T, 'abstract', r);
if length(abstract) > 500
    abstract = [abstract(1:497), '...'];
end

firstAuth = strtrim(local_col_str(T, 'first_author_name', r));
lastAuth  = strtrim(local_col_str(T, 'last_author_name', r));

lines = {};
lines{end+1} = sprintf('TY  - %s', risType);
if ~isempty(title)
    lines{end+1} = sprintf('TI  - %s', title);
end
if ~isempty(firstAuth)
    lines{end+1} = sprintf('AU  - %s', firstAuth);
end
if ~isempty(lastAuth) && ~strcmpi(lastAuth, firstAuth)
    lines{end+1} = sprintf('AU  - %s', lastAuth);
end
if ~isempty(yr)
    lines{end+1} = sprintf('PY  - %s', yr);
end
if ~isempty(srcName)
    switch risType
        case 'JOUR';  lines{end+1} = sprintf('JO  - %s', srcName);
        case 'CONF';  lines{end+1} = sprintf('T2  - %s', srcName);
        otherwise;    lines{end+1} = sprintf('T2  - %s', srcName);
    end
end
if ~isempty(doi)
    lines{end+1} = sprintf('DO  - %s', doi);
    lines{end+1} = sprintf('UR  - https://doi.org/%s', doi);
end
if ~isempty(abstract)
    lines{end+1} = sprintf('N2  - %s', abstract);
end
lines{end+1} = 'ER  - ';

entry = string(strjoin(lines, newline));
end

% ── Type mapping ──────────────────────────────────────────────────────────

function btype = local_bibtex_type(typeStr)
switch lower(strtrim(typeStr))
    case {'article', 'review', 'journal-article'}
        btype = 'article';
    case {'conference-paper', 'proceedings-article', 'conference'}
        btype = 'inproceedings';
    case {'book'}
        btype = 'book';
    case {'book-chapter'}
        btype = 'incollection';
    otherwise
        btype = 'misc';
end
end

function rtype = local_ris_type(typeStr)
switch lower(strtrim(typeStr))
    case {'article', 'review', 'journal-article'}
        rtype = 'JOUR';
    case {'conference-paper', 'proceedings-article', 'conference'}
        rtype = 'CONF';
    case {'book'}
        rtype = 'BOOK';
    case {'book-chapter'}
        rtype = 'CHAP';
    otherwise
        rtype = 'GEN';
end
end

% ── Utilities ───────────────────────────────────────────────────────

function v = local_col_str(T, col, row)
v = '';
if ~ismember(col, T.Properties.VariableNames)
    return;
end
raw = T.(col)(row);
if isstring(raw)
    if ~ismissing(raw)
        v = char(raw);
    end
elseif ischar(raw)
    v = raw;
elseif isnumeric(raw) && isscalar(raw) && ~isnan(raw)
    v = char(string(raw));
end
end

function s = local_bib_escape(s)
% Escape BibTeX special characters ({ } \ & % $ # ^ ~ _ — practically important ones)
if isempty(s); return; end
s = strrep(s, '\', '\\');
s = strrep(s, '{', '\{');
s = strrep(s, '}', '\}');
s = strrep(s, '&', '\&');
s = strrep(s, '%', '\%');
s = strrep(s, '$', '\$');
s = strrep(s, '#', '\#');
s = strrep(s, '_', '\_');
end

function T = local_load_data(inputPath)
p = char(inputPath);
if isfile(p)
    [~, ~, ext] = fileparts(p);
    if strcmpi(ext, '.jsonl')
        T = read_jsonl(inputPath);
    else
        T = readtable(p, "TextType", "string", ...
            "VariableNamingRule", "preserve", "Delimiter", ",", "ReadVariableNames", true);
    end
    return;
end
csvPath = strrep(p, '.jsonl', '.csv');
if isfile(csvPath)
    T = readtable(csvPath, "TextType", "string", ...
        "VariableNamingRule", "preserve", "Delimiter", ",", "ReadVariableNames", true);
    return;
end
error("export_bibtex:InputNotFound", "Input file not found: %s", inputPath);
end

function local_addpath_util(thisFileFullPath)
srcDir  = fileparts(thisFileFullPath);          % src/export/
utilDir = fullfile(srcDir, '..', 'util');
if isfolder(utilDir) && ~any(strcmp(strsplit(path, pathsep), char(string(utilDir))))
    addpath(char(utilDir));
end
end
